In [8]:
import pandas as pd

In [9]:
df = pd.read_csv(r'C:\Users\user\Desktop\Tp2 activity 5\Informal_Settlement_Programme_-1898186875815614491.csv')

In [10]:
# 1. Understanding the dataset
## Display the size of the dataframe
print(f"Size of the dataset: {df.shape}")

## Display the data types of each column
print("\nData types of each column:")
print(df.dtypes)

## Display column names
print("\nColumn names:")
print(df.columns)

## Display the first few rows of the dataframe
print("\nFirst few rows of the dataframe:")
print(df.head())

## Data slicing and indexing example
print("\nExample of data slicing and indexing:")
print(df.iloc[0:5, 0:5])  # Slicing the first 5 rows and first 5 columns

# 2. Identifying missing data
## Check for missing values in each column
print("\nMissing data in each column:")
print(df.isnull().sum())

# 3. Normalizing or standardizing data if required
## Example: Normalize the 'EST_HHC' column using Min-Max scaling
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
df['EST_HHC_normalized'] = scaler.fit_transform(df[['EST_HHC']])

print("\nFirst few rows after normalizing 'EST_HHC':")
print(df[['EST_HHC', 'EST_HHC_normalized']].head())

# Alternatively, Standardizing the 'EST_HHC' column
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
df['EST_HHC_standardized'] = scaler.fit_transform(df[['EST_HHC']])

print("\nFirst few rows after standardizing 'EST_HHC':")
print(df[['EST_HHC', 'EST_HHC_standardized']].head())

# Summary of the dataframe after pre-processing
print("\nSummary of the dataframe after pre-processing:")
print(df.describe(include='all'))

Size of the dataset: (566, 18)

Data types of each column:
OBJECTID           int64
NAME_OF_SE        object
ALT_NAME          object
STREETNAME        object
WARD_S            object
PLANNING_U        object
LATITUDE          object
LONGITUDE         object
REGION            object
WATER_SUPP        object
SANITATION        object
REFUSE            object
ELECTRIC_2        object
UNIREFCODE        object
EST_HHC            int64
NUSP_CAT          object
Shape__Area      float64
Shape__Length    float64
dtype: object

Column names:
Index(['OBJECTID', 'NAME_OF_SE', 'ALT_NAME', 'STREETNAME', 'WARD_S',
       'PLANNING_U', 'LATITUDE', 'LONGITUDE', 'REGION', 'WATER_SUPP',
       'SANITATION', 'REFUSE', 'ELECTRIC_2', 'UNIREFCODE', 'EST_HHC',
       'NUSP_CAT', 'Shape__Area', 'Shape__Length'],
      dtype='object')

First few rows of the dataframe:
   OBJECTID     NAME_OF_SE       ALT_NAME  \
0         1       Amatikwe
1         2  Congo Phase 2  Congo Phase 2
2         3  Africa Inanda         Africa
3         4        Namibia
4         5     Mshayazafe

                               STREETNAME  WARD_S  \
0                              MR93 North  56/108
1                        MR93 /MR93 North   55/57
2                  Curnick Ndlovu Highway      55
3  Curnick Ndlovu Highway / Matshana Road  108/44
4                            Sidudla Road      55

                      PLANNING_U           LATITUDE         LONGITUDE  \
0                       Amatikwe  -29,6847594568261  30,9331993743659
1                   Inanda Congo  -29,6930565996813  30,9524428875002
2        Ohlange-Africa / Stop 8   -29,700492743755  30,9486579023242
3                 Inanda Namibia   -29,703771886581  30,9335017254606
4  Mshayazafe / Ohlange - Africa  -29,7066784039778  30,9469610275001

     REGION                           WATER_SUPP  \
0  Northern                           Standpipes
1  Northern                           Standpipes
2  Northern  Ablution Facility Taps & Standpipes
3  Northern  Ablution Facility Taps & Standpipes
4  Northern                           Standpipes

                        SANITATION           REFUSE ELECTRIC_2 UNIREFCODE  \
0                      Pit Privies  C&SW contractor        Yes      I0005
1  Ablution Facility & Pit Privies  C&SW contractor        Yes      I0037
2                Ablution Facility  C&SW contractor        Yes      I0002
3                Ablution Facility  C&SW contractor        Yes      I0145
4                      Pit Privies  C&SW contractor        Yes      I0140

   EST_HHC NUSP_CAT   Shape__Area  Shape__Length
0     3250       B1  2.393433e+06   22801.689196
1      758       B1  2.894931e+05    4460.071000
2      627       B1  2.831338e+05    2289.974147
3     1508       B1  6.782034e+05    3987.698818
4      349       B1  1.393780e+05    1965.577993

Example of data slicing and indexing:
   OBJECTID     NAME_OF_SE       ALT_NAME  \
0         1       Amatikwe
1         2  Congo Phase 2  Congo Phase 2
2         3  Africa Inanda         Africa
3         4        Namibia
4         5     Mshayazafe

                               STREETNAME  WARD_S
0                              MR93 North  56/108
1                        MR93 /MR93 North   55/57
2                  Curnick Ndlovu Highway      55
3  Curnick Ndlovu Highway / Matshana Road  108/44
4                            Sidudla Road      55

Missing data in each column:
OBJECTID         0
NAME_OF_SE       0
ALT_NAME         4
STREETNAME       0
WARD_S           0
PLANNING_U       0
LATITUDE         0
LONGITUDE        0
REGION           0
WATER_SUPP       0
SANITATION       0
REFUSE           0
ELECTRIC_2       0
UNIREFCODE       0
EST_HHC          0
NUSP_CAT         0
Shape__Area      0
Shape__Length    0
dtype: int64

First few rows after normalizing 'EST_HHC':
   EST_HHC  EST_HHC_normalized
0     3250            0.324373
1      758            0.075347
2      627            0.062256
3     1508            0.150295
4      349            0.034476

First few rows after standardizing 'EST_HHC':
   EST_HHC  EST_HHC_standardized
0     3250              2.814113
1      758              0.239701
2      627              0.104369
3     1508              1.014504
4      349             -0.182824

Summary of the dataframe after pre-processing:
        OBJECTID NAME_OF_SE ALT_NAME            STREETNAME WARD_S PLANNING_U  \
count   566.0000        566      562                   566    566        566
unique       NaN        566      250                   503    152        230
top          NaN   Amatikwe           District Road No.403     83   Clermont
freq         NaN          1      305                     8     28         18
mean    283.5000        NaN      NaN                   NaN    NaN        NaN
std     163.5344        NaN      NaN                   NaN    NaN        NaN
min       1.0000        NaN      NaN                   NaN    NaN        NaN
25%     142.2500        NaN      NaN                   NaN    NaN        NaN
50%     283.5000        NaN      NaN                   NaN    NaN        NaN
75%     424.7500        NaN      NaN                   NaN    NaN        NaN
max     566.0000        NaN      NaN                   NaN    NaN        NaN

                 LATITUDE         LONGITUDE    REGION WATER_SUPP  \
count                 566               566       566        566
unique                561               561         3         49
top     -29,9026105096045  30,8352867394588  Southern        TBC
freq                    3                 3       273        137
mean                  NaN               NaN       NaN        NaN
std                   NaN               NaN       NaN        NaN
min                   NaN               NaN       NaN        NaN
25%                   NaN               NaN       NaN        NaN
50%                   NaN               NaN       NaN        NaN
75%                   NaN               NaN       NaN        NaN
max                   NaN               NaN       NaN        NaN

               SANITATION           REFUSE ELECTRIC_2 UNIREFCODE  \
count                 566              566        566        566
unique                 29                2         15        561
top     Ablution Facility  C&SW contractor        Yes      I0159
freq                  217              562        329          3
mean                  NaN              NaN        NaN        NaN
std                   NaN              NaN        NaN        NaN
min                   NaN              NaN        NaN        NaN
25%                   NaN              NaN        NaN        NaN
50%                   NaN              NaN        NaN        NaN
75%                   NaN              NaN        NaN        NaN
max                   NaN              NaN        NaN        NaN

             EST_HHC NUSP_CAT   Shape__Area  Shape__Length  \
count     566.000000      566  5.660000e+02     566.000000
unique           NaN       10           NaN            NaN
top              NaN       B1           NaN            NaN
freq             NaN      348           NaN            NaN
mean      525.971731      NaN  1.770229e+05    2347.667073
std       968.844647      NaN  4.949141e+05    2973.644491
min         4.000000      NaN  1.195089e+02      79.929137
25%        56.250000      NaN  5.714704e+03     521.062682
50%       177.000000      NaN  2.194467e+04    1168.496511
75%       608.250000      NaN  9.635537e+04    2891.325711
max     10011.000000      NaN  6.560964e+06   22801.689196

        EST_HHC_normalized  EST_HHC_standardized
count           566.000000          5.660000e+02
unique                 NaN                   NaN
top                    NaN                   NaN
freq                   NaN                   NaN
mean              0.052161         -6.904567e-17
std               0.096817          1.000885e+00
min               0.000000         -5.392335e-01
25%               0.005221         -4.852555e-01
50%               0.017288         -3.605123e-01
75%               0.060383          8.499923e-02
max               1.000000          9.798700e+00

### Data Types in Relation to Machine Learning

In the context of machine learning, the dataset contains various types of data that can be utilized for different purposes:

1. **Categorical Data**: This type of data represents discrete values or categories. Examples in the dataset include:
   - `REGION`: Represents different regions, each being a category.

2. **Numerical Data**: This type of data represents continuous or discrete numerical values. Examples in the dataset include:
   - `EST_HHC`: Represents the estimated household counts, a continuous variable.
   - `LATITUDE` and `LONGITUDE`: Represent geographical coordinates, continuous variables.

3. **Text Data**: This type of data includes free-form text. Examples in the dataset include:
   - `NAME_OF_SE`: Represents the name of the settlement.
   - `STREETNAME`: Represents the name of the street.

For machine learning, numerical data can be directly used for training models after normalization or standardization, while categorical data may need to be encoded (e.g., using one-hot encoding). Text data might require text processing techniques such as tokenization and embedding before being used in models.